My first pull request
Mike111222/Hello-Microverse-Project pull request #1
Opened 2023-04-25 18:32 UTC by Mike111222

2023-04-25 19:12 UTC, alexpuente0 requested changes
Hello, @Mike111222 

<img src="https://media3.giphy.com/media/U6jgliKTnrtCp5H8a9/giphy.gif"/>

You've done a great job so far!

In this case, however, there are still some issues that you need to work on to finish this project and advance to the next one, but you are almost there!

## Highlights
- Linters are correctly installed and every check is green 🟢 
- Repo looks professional
- Correct use of gitflow
- Gitignore file correctly implemented

## Required Changes ♻️ ⚠️ 
- Your Pull Requests should include a summary of what changes are you trying to implement, but in this case there was no description at all:
![image](https://user-images.githubusercontent.com/99830261/234377658-cb9faf1e-1903-4b95-ad07-eacaa899cf85.png)
It is important to be descriptive on what you are trying to merge into main, so please update this part and submit for a new review.
- Please remember not to erase this pull request and/or project, it is recommended that you work on the same repo/pull request as reviewers can keep track of the changes and improvements on the project. that have been suggested before.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 03:57 UTC, Efiamotu-1 requested changes
Hi @Mike111222 , 

![](https://camo.githubusercontent.com/a06454929d29b512682cd8b375641b59076b9e5fe1a367808e685e5bcb818de3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e32466d5957466c5a6a45794d7a49314f4455784d5455775a44686b595459355932526c4e6a4d334e7a4e6c4f574530596a4a684d695a6c634431324d563970626e526c636d35686246396e61575a7a583264705a6b6c6b4a6d4e305057632f7a3370696f6b77663057504838314d4f68752f67697068792e676966)

Great work on making the changes requested by a previous reviewer 👏 Your Code is Awesome! 💪
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Especially if that's is your first project 1️⃣. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better job** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive PR description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 03:57 UTC, Efiamotu-1 commented on README.md
- [ ] Please kindly ensure that when your readme looks professional and descriptive because this is what recruiters and clients get to see it is important to always make it very professional with all the necessary sections, information and links to assists developers and non developers use and run your project. :+1: 
- [ ] To achieve this microverse has provided us with a [readme template](https://github.com/microverseinc/readme-template) which i would like you to use. please in using this template ensure that you add all sections, only the `faq` section is optional, also ensure you remove all of the words describing how you should customise a section and make sure there are no broken link especially with the MIT license.
- [ ] please take all of these things into consideration and correct your readme like i noted earlier it is important for your readme to be professional for all of your projects. :+1: 
- [ ] you are currently partly making use of the template but some sections are missing and there are no links please work on those aspects :+1:

2023-04-26 03:57 UTC, Efiamotu-1 commented on README.md
- [ ] It is also important to use good PR title and summary when making a pull request attached below is an image of how your pr title and summary for this project should look like please make sure to make the correct changes before resubmitting for a new pull request. :+1: 
![good-pr](https://user-images.githubusercontent.com/89055502/234389170-2ece21cc-1ad3-46e1-8e31-cb39f5f8304d.png)
- [ ] Your summary in this pr is good but you need to edit your PR title to be more descriptive :+1:

2023-04-26 09:55 UTC, Olamarx approved these changes
Hi @Mike111222, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif"/>
## Highlights
- Linters passed ✔️ 
- Readme file professional ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 10:50 UTC, merged

2023-04-27 01:07 UTC, Mike111222 commented
Thank you all for your positive feedback. I got it approved with an extra
review but learned a lot. Thanks again

On Wed, Apr 26, 2023 at 8:57 AM Habeeb Efiamotu Musa Owolewa <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Mike111222 <https://github.com/Mike111222> ,
>
>
> <https://camo.githubusercontent.com/a06454929d29b512682cd8b375641b59076b9e5fe1a367808e685e5bcb818de3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e32466d5957466c5a6a45794d7a49314f4455784d5455775a44686b595459355932526c4e6a4d334e7a4e6c4f574530596a4a684d695a6c634431324d563970626e526c636d35686246396e61575a7a583264705a6b6c6b4a6d4e305057632f7a3370696f6b77663057504838314d4f68752f67697068792e676966>
>
> Great work on making the changes requested by a previous reviewer 👏 Your
> Code is Awesome! 💪
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
>
> There are some *few* issues 🐛 that you still need to work 🔧 on though
> to go to the next project ⏭️ but you are almost there! 🏃
> Don't Worry 🙏
>
> It's ok to have bugs in your code 🐛. Especially if that's is your first
> project 1️⃣. Please, see this code review as a *chance* for you to *learn*
> practical coding skills and learn *new tips* that can improve your code
> quality 💯 and help you *get a better job* 💼.
>
> *I am going to guide you on how to fix them down below. 🤓*
> Highlights 🎯
>
>    - ✔️ No linter Errors
>    - ✔️ Descriptive PR description
>    - The code is top-notch! 💯 and has a huge potential.
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
> Important Notes 📝
>
>    - Feel free to leave any questions or comments in the PR thread if
>    something is not 100% clear.
>    - Please, remember to tag me in your question so I can receive the
>    notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
>
> *Note:* Please, don't Merge This Pull Request yet. Only Merge when it is
> Approved ✅.
>
> Thank you for your time 🙏 and call me if you need help or clarification
> ☎️
>
>    - This is My *GitHub*: [image: @Efiamotu-1]
>    <https://github.com/Efiamotu-1/>
>    - This is My *Twitter*: [image: @EFYAMOTU]
>    <https://twitter.com/EFYAMOTU>
>    - This is My *Slack*: [image: Habeeb Efiamotu Musa] <https://slack.com>
>
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> On README.md
> <https://github.com/Mike111222/Hello-Microverse-Project/pull/1#discussion_r1177306778>
> :
>
>    - Please kindly ensure that when your readme looks professional and
>    descriptive because this is what recruiters and clients get to see it is
>    important to always make it very professional with all the necessary
>    sections, information and links to assists developers and non developers
>    use and run your project. 👍
>    - To achieve this microverse has provided us with a readme template
>    <https://github.com/microverseinc/readme-template> which i would like
>    you to use. please in using this template ensure that you add all sections,
>    only the faq section is optional, also ensure you remove all of the
>    words describing how you should customise a section and make sure there are
>    no broken link especially with the MIT license.
>    - please take all of these things into consideration and correct your
>    readme like i noted earlier it is important for your readme to be
>    professional for all of your projects. 👍
>    - you are currently partly making use of the template but some
>    sections are missing and there are no links please work on those aspects
>    👍
>
> ------------------------------
>
> On README.md
> <https://github.com/Mike111222/Hello-Microverse-Project/pull/1#discussion_r1177308286>
> :
>
>    - It is also important to use good PR title and summary when making a
>    pull request attached below is an image of how your pr title and summary
>    for this project should look like please make sure to make the correct
>    changes before resubmitting for a new pull request. 👍
>    [image: good-pr]
>    <https://user-images.githubusercontent.com/89055502/234389170-2ece21cc-1ad3-46e1-8e31-cb39f5f8304d.png>
>    - Your summary in this pr is good but you need to edit your PR title
>    to be more descriptive 👍
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Mike111222/Hello-Microverse-Project/pull/1#pullrequestreview-1401111232>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5K5QZEXIJLMKOW3QL6TDZ3XDCML3ANCNFSM6AAAAAAXLMH2RM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-27 01:09 UTC, Mike111222 commented
Thanks a lot sir. It was really helpful and I learned a lot. It
doesnt matter now that it cost me an extra review but I got it approved.
Thanks a lot again sir.

On Wed, Apr 26, 2023 at 2:55 PM Olaoluwa Owoeye ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @Mike111222 <https://github.com/Mike111222>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
> <https://camo.githubusercontent.com/5a3a0aeb695e1a0e7c9cb8c5ad662d6d8f791402d56af001a5a7e70f0a15d082/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966>
> Highlights
>
>    - Linters passed ✔️
>    - Readme file professional ✔️
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Mike111222/Hello-Microverse-Project/pull/1#pullrequestreview-1401622102>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5K5QZGZ5LL4JGJEOFCH46DXDDWIVANCNFSM6AAAAAAXLMH2RM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>